language: node_js
node_js:
  - "stable"
  - "4"
  - "6"
  - "8"

env:
  global:
    - BUILD_TIMEOUT=10000

script:
  - npm run test:register
  - npm run lint
  - node_modules/.bin/acorn --ecma5 dist/buble-browser.cjs.js > /dev/null
  - node_modules/.bin/acorn --ecma5 dist/buble-browser-deps.umd.js > /dev/null
